### ISSUE TITLE
Cintiq companion Hybrid touch device not fully recognized

### ISSUE THREAD

**Issue by azbulutlu** [linuxwacom/libwacom#214]
Recently started to re-use an old Wacom Companion Hybrid (android/display dual device) and ran into a strange issue. xsetwacom --list used to show 4 devices

Wacom ISDv5 307 Pen stylus             
Wacom ISDv5 307 Pen eraser               
Wacom ISDv5 307 Pad pad                  
Wacom ISDv5 309 Finger touch

currently the finger touch device seems to be missing on the listing. neither xsetwacom nor KDE's utility can correctly map the touch input as a result. (touch input still works with default settings which maps it to all screens) 

Thanks in advance for the help.

**Comment by jigpu** [comment]
Given that the touch still works, it is likely being picked up by the libinput driver rather than ours. Would you mind running our [sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) and attaching the generated tarball to this issue? It should provide us with the logs and config files necessary to get a better idea of what is going on.

**Comment by azbulutlu** [comment]
the tarball is attached.

[sysinfo.SP9eh4U9Hd.tar.gz](https://github.com/linuxwacom/libwacom/files/4228430/sysinfo.SP9eh4U9Hd.tar.gz)

**Comment by whot** [comment]
from the Xorg.log:

> [     8.694] (II) Using input driver 'libinput' for 'Wacom ISDv5 309 Finger'

so yeah, it's the libinput driver that does it and (apparently) KDE can't map that to a screen? You can either force the wacom driver for the touch device with the snippet below or use the `xinput map-to-output` tool instead of `xsetwacom`, it does the same thing anyway (iirc).


```
Section "InputClass"
  Identifier "Map touch to wacom"
  MatchProduct "Wacom ISDv5 309 Finger"
  MatchDevicePath "/dev/input/event*"
  Driver "wacom"
EndSection
```

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
