### ISSUE TITLE
Support Dell Inspiron 7591 2 in 1 and Dell Active Pen – PN350M

### ISSUE THREAD

**Issue by spike886** [linuxwacom/libwacom#215]
I bought a new Dell Inspiron 7591 2 in 1. The stylus is not found on the gnome configuration panel.
As soon as I touch the screen I see a notification saying that a wireless keyboard has 1% of battery remaining. I can be used 

**Device name**
Dell Active Pen 

**Device model identifier**
PN350M

**udevadm info output**
```
P: /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-CUST0000:00/0018:04F3:241E.0002/input/input24/event8
N: input/event8
L: 0
S: input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-CUST0000:00/0018:04F3:241E.0002/input/input24/event8
E: DEVNAME=/dev/input/event8
E: MAJOR=13
E: MINOR=72
E: SUBSYSTEM=input
E: USEC_INITIALIZED=3959006
E: ID_INPUT=1
E: ID_INPUT_TABLET=1
E: ID_INPUT_WIDTH_MM=342
E: ID_INPUT_HEIGHT_MM=194
E: ID_SERIAL=noserial
E: ID_PATH=pci-0000:00:15.1-platform-i2c_designware.1
E: ID_PATH_TAG=pci-0000_00_15_1-platform-i2c_designware_1
E: LIBINPUT_DEVICE_GROUP=18/4f3/241e:i2c-CUST0000:00
E: DEVLINKS=/dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse
```

I open an issue on https://github.com/linuxwacom/wacom-hid-descriptors, and the maintainer recommended to open another issue here
https://github.com/linuxwacom/wacom-hid-descriptors/issues/79

Here is the `libinput record` just in case [libinput_record.txt](https://github.com/linuxwacom/libwacom/files/4207707/libinput_record.txt)

**Comment by whot** [comment]
ftr, I replayed the recording here and at least libinput current master didn't crash like was suggested in linuxwacom/wacom-hid-descriptors#79. So either it's an older version that does crash or the crash is elsewhere.

There is nothing in the recording that jumps out at me, seems like a pretty standard device. At least from the libwacom side adding a tablet description should be fine.

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
