### ISSUE TITLE
Support for Huion WH1409?

### ISSUE THREAD

**Issue by pixeldanger** [linuxwacom/libwacom#25]
If I had a better idea of how to find the info I need, I'd make the .tablet file myself; unfortunately, digging through what info I did get from the sysinfo script didn't help me much.
I have included it-- thanks a bunch, if you happen to get it working.
[sysinfo.UTEF4Bvs3a.tar.gz](https://github.com/linuxwacom/libwacom/files/2104703/sysinfo.UTEF4Bvs3a.tar.gz)

**Comment by jigpu** [comment]
To be clear, do your Huion work at all or just not show up in the control panel? If it doesn't work at all, you'll need to file a bug at https://github.com/DIGImend/digimend-kernel-drivers which is where your tablet's drivers are developed. You can include a link back to this bug so that their developers can find the data you've collected.

**Comment by pixeldanger** [comment]
Sorry -- the pressure sensitivity and tracking of the input works fine, but the shortcut buttons do not.  xinput does see the tablet -- it reports back with "Pen Tablet Pad" and "Pen Tablet Pen", but I'm unable to configure it in the control panel.

**Comment by whot** [comment]
I recommend starting with the `data/huion-h610-pro.tablet` file in the linuxwacom repo, then going from there. Chances are this already somewhat matches (huion re-uses usb ids) so you may only have to add your match to that file.  But it's better to create a new file since the device has 12 buttons, not 8.

The EvdevCodes you can get with `evemu-record`, just use the hex humbers of whatever comes from the pad or match it with the #defines in `/usr/include/linux/input-event-codes.h`.

If the pad doesn't send buttons then you'll need a kernel fix - libwacom merely describes the tablet but doesn't affect how it works at all.

**Comment by whot** [comment]
Closing, it's been almost a year
