### ISSUE TITLE
tablet 'Network Tablet' unknown to libwacom .. software gfxtablet how to create data file?

### ISSUE THREAD

**Issue by asdf23** [linuxwacom/libwacom#259]
**Device name**
> Network Tablet

**Device model identifier**
Need help trying to determine this output of evemu-record is attached. 
[NetworkTabletEvemuRecord.txt](https://github.com/linuxwacom/libwacom/files/4776144/NetworkTabletEvemuRecord.txt)

This device is emulated by software, and not listed.

**udevadm info output**
> attached 
[NetworkTabletUdevadmInfo.txt](https://github.com/linuxwacom/libwacom/files/4776149/NetworkTabletUdevadmInfo.txt)

An error from Xorg.0.log  "tablet 'Network Tablet' unknown to libwacom" is what brought me here. I'm trying to attach an external tablet to act as a writing device using "GfxTablet" (https://github.com/rfc2822/GfxTablet).  I would like to try creating a tablet file in /usr/share/libwacom but I am uncertain of the correct format. I understand that this is an unusual edge case.
Thank you

**Comment by whot** [comment]
check the existing files in `data/*.tablet`, depending on your capabilities you need to pick a comparable one. Most likely any of the ISDV4 class will do, just check recent commits.

Having said that, that error comes from libinput which uses libwacom to check for certain capabilities, none of which likely matter if your device is software controlled anyway because you can affect those capabilities at that level. So easiest is to just ignore the warning.

**Comment by whot** [comment]
A follow-up on this: libwacom now supports loading `.tablet` files from `/etc/libwacom` so for your use-case, dropping the file in there is the best solution. This way it won't get wiped/overwritten on update and you can custom-tailor  it to whatever the software tablet is configured to look like.

**Comment by whot** [comment]
See comment above, for software devices that's about the best we can do.
