### ISSUE TITLE
Intuos S (In Mint Cinnamon 20)

### ISSUE THREAD

**Issue by dm2912** [linuxwacom/libwacom#281]
Hi all. 

I will start by saying, I do not know if this is a libwacom issue, a cinnamon issue or a driver issue but this git seems the best place to start troubleshooting, and if its not a libwacom issue feel free to send me somewhere else :D

Wacom Intuos S on Cinnamon 20.

The tablet actually works fine, I am able to setup custom configs using xsetwacom, pressure works in gimp/krita etc

The issue I am having is I am unable to access graphic settings for the device via cinnamon settings and it errors out with the following

`(cinnamon-settings.py:8903): wacom-cc-panel-WARNING **: 23:57:27.349: Could not set the current stylus ID 0x0 for tablet 'Wacom Intuos S', no general pen found
**
wacom-cc-panel:ERROR:csd-wacom-device.c:1890:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)
Bail out! wacom-cc-panel:ERROR:csd-wacom-device.c:1890:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)
Aborted (core dumped)
`

So i guess the first question is is this a libwacom issue or is it something i should be directing at the cinnamon team?

Device Identifier:

$ xsetwacom --list
Wacom Intuos S Pen stylus       	id: 12	type: STYLUS    
Wacom Intuos S Pad pad          	id: 13	type: PAD       
Wacom Intuos S Pen eraser       	id: 19	type: ERASER    
Wacom Intuos S Pen cursor       	id: 20	type: CURSOR  

Sysinfo https://cloud.dimspace.xyz/s/sRYRAExZLkk4XxD

**Comment by jigpu** [comment]
Searching for that assertion turns up https://bugzilla.redhat.com/show_bug.cgi?id=799667, which also links to https://bugzilla.gnome.org/show_bug.cgi?id=672917. Cinnamon hasn't really touched its Wacom code in ages, so I have to wonder if you're experiencing this same ancient bug...

One workaround was apparently to define an eraser in the list of supported styli. Try editing `/usr/share/libwacom/intuos-s-p3.tablet` and change the line `Styli=@intuospt3;` to `Styli=@intuospt3;0xffffe`. After that reboot and see if its made any difference.

**Comment by dm2912** [comment]
Error persists after that edit unfortunately.

Just tested in gnome control center, that sees the tablet but no stylus.

its not the end of the world, was able to configure the buttons via xsetwacom (once i worked out that while buttons 1-3 were numbered 1-3 but button 4 was numbered 9). only the stylus buttons i cannot configure. and no per-application settings

**Comment by ThomHPL** [comment]
I randomly tried things, and changing the line `Styli=@intuospt3;` to `Styli=0x862;0xffffe;` in `/usr/share/libwacom/intuos-s-p3.tablet` made it working.

The settings window appears, every setting seems to work (I haven't tried the map to monitor options).

I tried also `Styli=@intuospt3;0xffffe` afterwards, and it still works.

**Comment by dm2912** [comment]
Aha, now i see why @jigpu 's solution did not work for me.. that crucial ";"

"Styli=0x862;0xffffe;" not "Styli=0x862;0xffffe"

**Comment by toohuman** [comment]
This change also worked for me using the CTL-4100WL on Linux Mint 20. Before this change, the settings page would open if the tablet wasn't connected, but would immediately close when attached.

**Comment by rjv23** [comment]
Hi;
thank you for the reply.

YES, this works. made changes to /usr/share/libwacom ; changing the line Styli=@intuospt3; to Styli=0x862;0xffffe; in /usr/share/libwacom/intuos-s-p3.tablet (find your correct model number) works, the graphic tablet icon in system settings opens a tablet configuration dialogue.

thank you so much for the reply

**Comment by fabiojmf** [comment]
> Searching for that assertion turns up https://bugzilla.redhat.com/show_bug.cgi?id=799667, which also links to https://bugzilla.gnome.org/show_bug.cgi?id=672917. Cinnamon hasn't really touched its Wacom code in ages, so I have to wonder if you're experiencing this same ancient bug...
> 
> One workaround was apparently to define an eraser in the list of supported styli. Try editing `/usr/share/libwacom/intuos-s-p3.tablet` and change the line `Styli=@intuospt3;` to `Styli=@intuospt3;0xffffe`. After that reboot and see if its made any difference.

it worked for me. Thank you

**Comment by lajossoukup** [comment]
It is import to edit the right config file. I located it using the following method. 
1.Go to the folder: 
         lsoukup@szusszancs:/$ cd /usr/share/libwacom/
2.Determine the type of your wacom table:
      lsoukup@szusszancs:/usr/share/libwacom$ xsetwacom --list devices
      Wacom Intuos BT M Pen stylus    	id: 8	type: STYLUS    
      Wacom Intuos BT M Pad pad       	id: 9	type: PAD       
      Wacom Intuos BT M Pen eraser    	id: 22	type: ERASER    
      Wacom Intuos BT M Pen cursor    	id: 23	type: CURSOR    
3.Determine the file which contains the confiduration of your  tablet:
       lsoukup@szusszancs:/usr/share/libwacom$ find . -exec grep "Wacom Intuos BT M" {} \; -print 2>/dev/null
       Name=Wacom Intuos BT M (Android Mode)
       ./intuos-m-p3-wl-android.tablet
       Name=Wacom Intuos BT M
      ./intuos-m-p3-wl.tablet
 4. Finally I replaced the line 
     Styli=@intuospt3
with 
     Styli=@intuospt3;0xffffe
in the file intuos-m-p3-wl.tablet

**Comment by silverstorm** [comment]
Thanks @lajossoukup for the steps.

For future readers:
Quicker way to do step 3: grep -rw . -e 'Wacom Intuos BT M'

And you don't have to reboot if you unload and reload the wacom module

sudo modprobe -r wacom
sudo modprove wacom

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks

**Comment by rjv23** [comment]
what are you talking about? all I did was told you something is not working, you can fix it or not, up to you. I am not filing any request or other nonsense. no wonder linux desktops arent very popular....pls nevermind to bother me with this again.

    On Wednesday, August 3, 2022 at 11:13:58 AM GMT+8, Peter Hutterer ***@***.***> wrote:  
 
 


This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:
   
   - if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
   - if the device is missing a .tablet file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
   - if the device has a .tablet file but that file is buggy or libwacom does the wrong thing (check libwacom list-local-devices), please file a new bug.

Thanks

**Comment by IsaacNez** [comment]
Hi everyone! 

This guide does seem to fix the error but it continues to appear while the Intuous BT M is connected through USB.

Does anyone have an idea how to fix it?
