### ISSUE TITLE
Id for Stylus used with Volito2?

### ISSUE THREAD

**Issue by semla** [linuxwacom/libwacom#299]
I have created a `.tablet` file for Volito2. But I can't get the pen to show up in Gnome Settings. How can I find the value for the Styli line?

**Comment by whot** [comment]
easiest to use the `libinput debug-tablet` tool (libinput 1.15 and later). it'll show the stylus id when you get it into proximity.

**Comment by jigpu** [comment]
I believe the Volito2 tablets are based on the same tech as the Bamboo/Graphire. I don't believe there will be a stylus ID, but the tool above should make that clear.

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
