### ISSUE TITLE
Help to submit new device (Acer Switch 3)

### ISSUE THREAD

**Issue by Fef0** [linuxwacom/libwacom#310]
Hi, I generated the tarball from the **sysinfo script**: [sysinfo.QRtpxJFVEh.tar.gz](https://github.com/linuxwacom/libwacom/files/5610664/sysinfo.QRtpxJFVEh.tar.gz)
but I'm still confused on how I should act now in order to submit a new device request.
I found that the device name is **04F3224A:00 04F3:24FE** and that it is attached to the libinput **event8** but I can't find the exact **DeviceMatch** and all the other info that are requested (such as Class, Width, Stily, ecc..)

Can someone point me where to find those parameters?
Thank you in advance for the help.

**Comment by jigpu** [comment]
Can you create an issue at https://github.com/linuxwacom/wacom-hid-descriptors/issues with the sysinfo attached? I'd like to add your device to the repository for future reference.

As for the information you'll need to create a new tablet definition, the DeviceMatch is just the bus/vid/pid, so "i2c:04f3:24fe" and the width/height can be read from the HID descriptor (it looks like 11" by 6"). I'm not sure what the stylus line should be, however... I don't know if Elan devices are capable of sending stylus IDs...

**Comment by Fef0** [comment]
Hi @jigpu, thanks for the reply, I'm going to open a new issue on wacom-hid-descriptors right now.
I already tried to create a tablet definition but without success.
Since I noticed that others have omitted width and height, I tried the following (filename is 04F3224A_00-04F3_24FE.tablet)
```
[Device]
Name=04F3224A:00 04F3:24FE
ModelName=
DeviceMatch=i2s:04f3:24fe
Class=ELAN
IntegratedIn=Display;System


[Features]
Stylus=true
Touch=true
Buttons=0
```
I'm not sure about the Class though.
What am I doing wrong?

**Comment by jigpu** [comment]
At the very least you'll need to change `DeviceMatch=i2s:04f3:24fe` to `DeviceMatch=i2c:04f3:24fe`. Hopefully that is enough to get things working...

**Comment by Fef0** [comment]
It worked, thank you very much @jigpu , I didn't notice the subtle misspelling.
I confirm that the tablet is correctly displayed in the Wacom settings now.
The pen is not, unfortunately. Any ideas?
Maybe it's just my impression, but can it be possible that the pen is detected as a mouse/finger?
Because I noticed that the trait itself and the pen tip have a gap proportional to the speed in which I write. For example if I draw a straight line really fast the trait would be pretty far away, but once I stop and the gap between the end of the trait and the tip is shorter, the trait itself accelerates. It's different to explain, I hope you got the idea.
It's my first tablet so I don't really know if that's normal.
Thanks again for the help

**Comment by jigpu** [comment]
I really can't help too much with Elan hardware, but I suspect the hardware (if its anything like Wacom's) treats the pen as a very "special" kind of finger. The gap you describe is pretty normal for any kind of pen technology, however -- the hardware only reads the new position of pen/touch input every so often.

I'd guess the issue with the pen not showing up is most likely due to the "Styli" line needing to be populated with something. Again, I'm not really sure what it should be there. @whot is the expert (especially for the non-Wacom devices), so maybe he can help :)

**Comment by Fef0** [comment]
Ok, I'll wait for him and then I'll eventually push my .tablet file once I'll have tested it.
Thank you again @jigpu, you've been extremely kind!

**Comment by whot** [comment]
>  The pen is not, unfortunately. Any ideas?

if you're using Wayland, the pen won't show up until you bring it into proximity once. Could that simply be the issue?

>  Maybe it's just my impression, but can it be possible that the pen is detected as a mouse/finger?

`libinput record` records the kernel devices, if you can attach a short sequence of that we'll be able to figure out what's going on.
and a good second check is `libinput debug-events`, that'll print out the events that come out of libinput and may hint at some issues. If you don't see a lot of `TABLET_*` events, then the issue is in libinput (or the kernel).

> the "Styli" line needing to be populated with something

Yeah, one of the generic pens, but don't ask me which one :) One of `0xfffff`, `0xffffe` or `0xffffd`, see the top entries for the `data/libwacom.stylus` file and use whichever comes closest.

**Comment by Fef0** [comment]
@whot I tried all the methods you described and the pen actually works and is recognized by libinput. It just doesn't show in the Wacom settings. I'm using X11 since Wayland is unstable in my system and moving the pen near the screen doesn't make any difference.
Here's the outputs of the commands:
[libinput-record.txt](https://github.com/linuxwacom/libwacom/files/5641649/libinput-record.txt)
[libinput-debug-events.txt](https://github.com/linuxwacom/libwacom/files/5641650/libinput-debug-events.txt)

I tried to list the wacom devices detected by the system and actually the pen is recognized as part of the tablet:
[libwacom-list-local-devices.txt](https://github.com/linuxwacom/libwacom/files/5641651/libwacom-list-local-devices.txt)

**Comment by whot** [comment]
> I tried to list the wacom devices detected by the system and actually the pen is recognized as part of the tablet:

tbf, this tool just checks the evdev event nodes, fetches their VID/PID and then matches those against the known tablets in the database before printing whatever it knows about that device. So the `Styli=` line here will always match whatever you specified in the `.tablet` file, there is no code to specifically handle the pen itself.

The `libinput debug-events` output looks correct, so right now I'm going to claim this is a bug somewhere in mutter and/or the control center where it doesn't process something correctly. though iirc they don't have wacom-vendor specific code and don't care whether it's a wacom or elan or anything else.

**Comment by Fef0** [comment]
@whot okay, thank you.
I noticed another issue: when I flip the tablet vertically the pen is mapped correctly but the eraser (which is mapped in the first button by default) is mapped as if it was used horizontally, any idea?

**Comment by whot** [comment]
what desktop environment do you use? libwacom is just a C api around the textual description, so it doesn't affect behaviour directly, other componets *use* libwacom to then change what happens. e.g. gnome uses the `IntegratedIn` values to auto-map to a monitor.

If the stylus is rotated correctly but the eraser isn't, that's an issue unrelated to libwacom, it's somewhere either in the Wayland compositor or in the X stack.

**Comment by Fef0** [comment]
@whot I'm actually stuck with X11 since Wayland has a lot of issues with my particular model. I tried under Wayland just to test it and the rotation actually works, so I guess X11 is the issue.
Thank you very much for your help, can I push my working .tablet file in the repo?

**Comment by whot** [comment]
under wayland, there's only libinput and it uses libwacom to identify touchscreens associated with the tablet. Where one is rotated, the other one is (transparently) rotated too. 

there's a reasonable chance that in X you end up using the wacom driver for the tablet and the libinput (or evdev) driver for the touchscreen. because drivers don't/can't talk to each other, the DE must know about the association between the two and rotate both. You could work around this by assigning the libinput driver to the tablet too (just uninstall the wacom driver) and with a bit of luck you won't even notice. the wacom driver has specific behaviours and some application may rely on them, so YMMV but you won't know until you tried ;)

as for the `.tablet` file - please do submit a PR and we can get it in.

**Comment by Pandayeyes** [comment]
Hello, i also wanna add a new device since it seems my model of tablet pc is not liste, where does the tarball file is stored ?

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
