### ISSUE TITLE
Acer Spin 5

### ISSUE THREAD

**Issue by Curious-Octopus** [linuxwacom/libwacom#33]
Good day. I am trying to add support for my Acer Spin 5's Pen(2 in 1 pc). However I have an issue. I cannot edit the stylus. One button acts as a middle mouse. The other seems blank. Stylus settings won't detect a stylus. Tablet is detected though.

```
[Device]
Name=ELAN Touchscreen Pen Pen (0)
DeviceMatch=usb:04f3:2560
IntegratedIn=Display;System

[Features]
Stylus=true
Touch=false
Buttons=0
```

```
[Device]
Name=ELAN Touchscreen Pen Pen (0)
DeviceMatch=usb:04f3:2560
IntegratedIn=Display;System
Styli=0xfffff;0xffffe

[Features]
Stylus=true
Reversible=false
Touch=false
TouchSwitch=false
Ring=false
Ring2=false
NumStrips=0
Buttons=2
```

**Comment by jigpu** [comment]
Hi there! Would you mind running our [sysinfo.sh script](https://github.com/linuxwacom/wacom-hid-descriptors/blob/master/scripts/sysinfo.sh) and attaching its output here? This will help us in the future if others need support for this device.

The tablet definitions you have here look reasonable; have you tried adding them to the `/usr/share/libwacom` directory and rebooting? If they're there with the other tablet definitions then the GNOME Control Center should detect your device and allow some basic configuration. Do note that you won't be able to configure the button that doesn't appear to do anything since its hard-wired to make the pen act as an eraser (which only programs like GIMP will care about).

**Comment by Curious-Octopus** [comment]
Hello friend =D I have tested them in libwacom. upon adding them my screen rotation would orient the pen correctly instead of in reverse. 
[sysinfo.wBHD8T7IwO.tar.gz](https://github.com/linuxwacom/libwacom/files/2288970/sysinfo.wBHD8T7IwO.tar.gz)

**Comment by Curious-Octopus** [comment]
I end up using this for my pc
[Acer Pen.zip](https://github.com/linuxwacom/libwacom/files/2292457/Acer.Pen.zip)

**Comment by jigpu** [comment]
Sorry for the delay in responding... Can you try replacing your 'Acer-Spin-5-13-Pen.tablet' file with the attached one (you'll need to decompress it first)? If it works, I'll send it to the mailinglist for integration into the next libwacom release.

[elan-2560.tablet.gz](https://github.com/linuxwacom/libwacom/files/2307204/elan-2560.tablet.gz)

**Comment by jigpu** [comment]
Any update on the provided tablet file?

**Comment by whot** [comment]
Closing, no updates for several months
