### ISSUE TITLE
I can't map the tablet buttons via bluetooth [INTUOS BT S - CTL-4100WL]

### ISSUE THREAD

**Issue by alohl669** [linuxwacom/libwacom#359]
Hello!! seems like a simple bug, however it is quite uncomfortable. The issue is that if I connect via cable, I can configure all the buttons on the tablet fine, whereas if I connect the tablet via Bluetooth, the options to configure those buttons do not even appear. The rest, pen and its buttons work perfectly.

Info:
My Distro:
ubuntu 20.04
5.10.17-051017-generic

BT USB:
`Bus 001 Device 010: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)`
dmesg info pluggin usb BT:
```
[21810.700106] usb 1-1: new full-speed USB device number 11 using xhci_hcd
[21810.832120] usb 1-1: device descriptor read/64, error -71
[21811.076113] usb 1-1: device descriptor read/64, error -71
[21811.312090] usb 1-1: new full-speed USB device number 12 using xhci_hcd
[21811.500097] usb 1-1: New USB device found, idVendor=0a12, idProduct=0001, bcdDevice=88.91
[21811.500101] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[21811.506097] Bluetooth: hci0: unexpected event for opcode 0x0000
```
**wacom w/cable info:**
xsetwacom --list:
```
Wacom Intuos BT S Pen stylus    	id: 18	type: STYLUS    
Wacom Intuos BT S Pen eraser    	id: 19	type: ERASER    
Wacom Intuos BT S Pen cursor    	id: 20	type: CURSOR    
Wacom Intuos BT S Pad pad       	id: 21	type: PAD
```
libwacom-list-local-devices:
```
# Device node: /dev/input/event23
[Device]
Name=Wacom Intuos BT S
ModelName=CTL-4100WL
DeviceMatch=usb:056a:0376;bluetooth:056a:0377;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
# Device node: /dev/input/event22
[Device]
Name=Wacom Intuos BT S
ModelName=CTL-4100WL
DeviceMatch=usb:056a:0376;bluetooth:056a:0377;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
```
**wacom w/bt info:**
xsetwacom --list:
```
Wacom Intuos BT S Pen stylus    	id: 18	type: STYLUS    
Wacom Intuos BT S Pad pad       	id: 19	type: PAD
```
libwacom-list-local-devices:
```
# Device node: /dev/input/event23
[Device]
Name=Wacom Intuos BT S
ModelName=CTL-4100WL
DeviceMatch=usb:056a:0376;bluetooth:056a:0377;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
# Device node: /dev/input/event22
[Device]
Name=Wacom Intuos BT S
ModelName=CTL-4100WL
DeviceMatch=usb:056a:0376;bluetooth:056a:0377;
Class=Bamboo
Width=6
Height=4
IntegratedIn=
Layout=intuos-s-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
```

**Comment by y-usuzumi** [comment]
Hi, I have the same issue. In `xev -event button` window only the rightmost button is registered. Other buttons do nothing.

**Comment by whot** [comment]
libwacom is a glorified database to look up device info otherwise not easily available, it doesn't affect the device and how it works - in the above it merely says "this device has 4 buttons with evdev codes blah", that's all libwacom does.

If the button doesn't do anything it's
- a kernel issue: run `libinput record` and press the button - if an event shows up and matches the evdev codes listed, it's not the kernel
- a libinput issue (for Wayland): run `libinput debug-events` and press the button - if an event shows up it's not a libinput issue

if it's neither, it's unlikely the xf86-input-wacom driver either because it doesn't use libwacom and just uses whatever kernel description the device has. If you're running GNOME it's most likely an issue with the button remapping in mutter/gnome-control center.

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
