### ISSUE TITLE
XP-PEN Star 03 not detected by GNOME settings

### ISSUE THREAD

**Issue by tj314** [linuxwacom/libwacom#420]
# General description
I have a brand new XP-PEN Star 3. I am running Fedora 34 Workstation with GNOME 40.1.0 on Wayland. When I plug in the tablet, it works. The pen behaves as another mouse input, different pressure levels work OK (tested in xournal++). I wanted to restrict the tablet to my primary screen, because I use dual monitors.

# Expected behavior
The tablet is detected by the GNOME settings.

# Actual behavior
The tablet is not detected the GNOME settings.

# What I tried
I ran:
```
$ libwacom-list-devices
...
- { bus: 'usb',       vid: '0x5543', pid: '0x0081', name: 'XP-Pen Star 03' }
- { bus: 'usb',       vid: '0x5543', pid: '0x0081', name: 'XP-Pen Star 03' }
...
```
Based on these entries, I assume my tablet is supported (though I'm not sure why there are two identical entries). Then I ran:
```
$ sudo libwacom-list-local-devices
/dev/input/event5 is a tablet but not supported by libwacom
Failed to find any devices known to libwacom.
$ sudo libwacom-show-stylus
Using "UGTABLET 10 inch PenTablet": /dev/input/event5
Using stylus file(s): /usr/share/libwacom/libwacom.stylus
Device only supports generic styli
```
I also ran `libwacom-update-db` without any success.

# Sidenotes
This my first time ever filing a bug report. I hope I provided all the required data, but will gladly answer all the questions. I would like to help with fixing this issue, given I have access to the tablet in question. I will need instructions though.

**Comment by whot** [comment]
It's listed twice because it has two entries with the same pid/vid but a different name match. That's fine, can be ignored.

Having said that, the match is `DeviceMatch=usb:5543:0081:UC-Logic TABLET 1060N Pen;usb:5543:0081:UC-Logic TABLET 1060N Pad`, which doesn't match your device name of `UGTABLET 10 inch PenTablet`, so libwacom just doesn't know about that device. Adding that as an extra entry to the `DeviceMatch` line in the `xp-pen-star03.tablet` should make it work.
