### ISSUE TITLE
XP-Pen Artist 12 tablet works except buttons and the touch strip do not!

### ISSUE THREAD

**Issue by zenny** [linuxwacom/libwacom#422]
**Device name**
XP-Pen Artist 12

**DeviceURL**
https://www.xp-pen.com/product/64.html

**Issue**
The libwacom driver that comes with linux kernel 5.4.x automatically detects everything except the 6 buttons and touch strip on the tablet itself.

See https://github.com/DIGImend/digimend-kernel-drivers/issues/556#issuecomment-907855182

**udevadm info output**

Tried with Digimed, yet without success. The technical details are posted in https://github.com/DIGImend/digimend-kernel-drivers/issues/554 and in https://github.com/DIGImend/digimend-kernel-drivers/issues/556

Cheers,

**Comment by whot** [comment]
libwacom is just a textual description of the device, it has no (or little) effect on whether the tablet works. Your problem is either in the kernel or in the userspace driver (either xf86-input-wacom or libinput). If the kernel doesn't send the right events, nothing in userspace can work correctly, so please work with the digimend project to get those patches into the kernel.
