### ISSUE TITLE
Doesn't work on HP envy x360 13-ay0xxx in Combination with HP Tilt pen MPP 2.0

### ISSUE THREAD

**Issue by Plamper** [linuxwacom/libwacom#431]
I have said Laptop with said Pen. The Pen sort of works but is recognised as a secondary mouse, not as a pen. The Devices name in GNOME Settings is `ELAN2514:00 04F3:2AF2`. It does only show up in the power menu. I tried to add the id to the corresponding file in `/usr/share/libwacom` but that didn't work. Any suggestions? On Fedora 35 beta

**Comment by whot** [comment]
This is a mass closure of bugs requesting device support and that haven't seen changes in a year or longer. If the issue is still present:

- if the device does not work, this is not a libwacom issue. libwacom merely describes the device, it doesn't affect it otherwise
- if the device is missing a `.tablet` file, please file a pull request with a tablet file attached. Using one of the existing data files will help, ideally search for a similar model
- if the device has a `.tablet` file but that file is buggy or libwacom does the wrong thing (check `libwacom list-local-devices`), please file a new bug.

Thanks
