### ISSUE TITLE
libwacom_new_from_path() fails in mocked environment

### ISSUE THREAD

**Issue by hadess** [linuxwacom/libwacom#438]
umockdev doesn't support mocking device nodes, so `libwacom_new_from_path()` fails to find devices after calling `g_udev_client_query_by_device_file()` which always fails.

One possible fix is it use something like `g_udev_client_query_by_subsystem_and_device_file()` (https://gitlab.gnome.org/GNOME/libgudev/-/merge_requests/22) or copy/paste it, so that there's no I/O made at all, and all the data comes from the udev database.

**Comment by hadess** [comment]
Ugly diff. Let me know if that would be a good way to fix this problem, and I'll prepare a PR.

```patch
diff --git a/libwacom/libwacom.c b/libwacom/libwacom.c
index 935344c..f496343 100644
--- a/libwacom/libwacom.c
+++ b/libwacom/libwacom.c
@@ -195,6 +195,22 @@ get_bus (GUdevDevice *device)
        return bus_str;
 }
 
+static GUdevDevice *
+my_udev_client_query_by_device_file (GUdevClient *client,
+                                    const char  *subsystem,
+                                    const char  *path)
+{
+       GList *l;
+       g_autolist(GUdevDevice) devices = NULL;
+
+       devices = g_udev_client_query_by_subsystem (client, subsystem);
+       for (l = devices; l != NULL; l = l->next) {
+               if (g_strcmp0 (g_udev_device_get_device_file (l->data), path) == 0)
+                       return g_object_ref (l->data);
+       }
+       return NULL;
+}
+
 static gboolean
 get_device_info (const char            *path,
                 int                   *vendor_id,
@@ -217,7 +233,7 @@ get_device_info (const char            *path,
        *name = NULL;
        bus_str = NULL;
        client = g_udev_client_new (subsystems);
-       device = g_udev_client_query_by_device_file (client, path);
+       device = my_udev_client_query_by_device_file (client, subsystems[0], path);
        if (device == NULL) {
                libwacom_error_set(error, WERROR_INVALID_PATH, "Could not find device '%s' in udev", path);
                goto out;
@@ -587,7 +603,7 @@ libwacom_new_from_path(const WacomDeviceDatabase *db, const char *path, WacomFal
 out:
        g_free (name);
        if (ret == NULL)
-               libwacom_error_set(error, WERROR_UNKNOWN_MODEL, NULL);
+               libwacom_error_set(error, WERROR_UNKNOWN_MODEL, "unknown model");
        return ret;
 }
 
```

**Comment by whot** [comment]
LGTM for the approach. I think we might still need the fallback if `device` ends up being `NULL` so it works with symlinks to device nodes like `/dev/input/by-id/...`. Or we call `readlink()` on the path which should then work correctly.

Another alternative I could think of is manually constructing a path equivalent to `/sys/class/input/$(basename path)` with the last element based on the input path. Still requires resolving links and the fallback so it doesn't really gain us that much.

Oh, and better to clean up the list manually instead of `g_autolist`. I wouldn't mind switching to autoptrs eventually but for now let's be consistent.
