### ISSUE TITLE
Found duplicate strings 

### ISSUE THREAD

**Issue by TheInfamousGrim** [linuxwacom/libwacom#464]
Found a duplicate string in an older file from January 2021.
Caused an error when I ran libwacom-list-local-devices
duplicate string: usb:256c:006e
Old File: gaomon-s56k.tablet

Fixed it for my self by deleting the older file.

New to this so I might have phrased that wrong. Hope this is helpful.

All the best!

**Comment by whot** [comment]
the 06e device ID is reused by a bunch of devices which is why we had to remove that file, see c7c4adb0ccd25fc569c8e60983c1ae1d7ea9fa7b. This should've been automatically done by the package manager unless you had a direct source install in which case what you did was fine, removing it is the right way to fix this.

So, not a bug, just a stale local file. Thanks though :)
