### ISSUE TITLE
Missing linux wacom tablet definition file for Microsoft Surface Pro 2

### ISSUE THREAD

**Issue by wittsend** [linuxwacom/libwacom#516]
**Device name**

> Microsoft Surface Pro 2

**Device model identifier**

> 256GB

**udevadm info output**

Please refer to this [issue ](https://github.com/linuxwacom/wacom-hid-descriptors/issues/176)at linuxwacom repo

**Comment by whot** [comment]
Please file a pull request with the `.tablet` file attached so we can run all the tests etc. Plus this way you can check locally if the resulting file actually works since we don't have the same device.

Commit 8502c79b67e77abdccd6ea0a54288ba9f97f7a4a added what looks like a similar device, you can use that as a guide.
