### ISSUE TITLE
Fujitsu T935 broken in Ubuntu 22.10....

### ISSUE THREAD

**Issue by frohro** [linuxwacom/libwacom#551]
Hi,
About a year ago I worked with your team to get the T935 recognized, and it worked with Ubuntu 22.04 just fine, but upon upgrading to 22.10 the stylus and tablet seem to be recognized as the wrong thing.  I suspect we messed up on some features they were not using in 22.04 or something.  Here is the [bug report](https://bugs.launchpad.net/ubuntu/+source/libwacom/+bug/2002215) I made to ubuntu, which has more info.  Any ideas on how to figure this out?
Thanks,
Rob

**Comment by whot** [comment]
At least from the libwacom side the data file is still in `data/isdv4-5019.tablet` and a quick peek at the bug report shows that the device is identified correctly by libwacom. Which means this bug is elsewhere, most likely in the compositor (since you're on wayland) or possibly in the control-center.

libwacom is just a database with a C api, so if it returns the right data, then its job is done.

btw `xinput` is mostly useless under Xwayland, see [this post](https://who-t.blogspot.com/2016/12/the-future-of-xinput-xmodmap-setxkbmap.html).
