### ISSUE TITLE
huion wh1409. not sure if its a bug or new request

### ISSUE THREAD

**Issue by samuraied** [linuxwacom/libwacom#553]
i have been attempting to use huion wh1409 for several days now. he is a list of what i have tried.
- using DIGImend dkms
-  searched the issues tab on git-hub for possible solutions or workarounds
- followed multiple fixes online, none of them worked.
- confirmed the tablet working on windows and recognised in my linux terminal.
- used OpenTabletDriver, and even went to their discord server to seek help, sadly nothing worked.
- i did check https://github.com/linuxwacom/libwacom/issues/25

my machine is
linux fedora 37 gnome on wayland.
nvidia 1080ti latest driver.

any help or guide is appreciated.

**Comment by whot** [comment]
Please see https://github.com/linuxwacom/libwacom/wiki/Adding-a-new-device

**Comment by whot** [comment]
From libwacom's POV you can add a `.tablet` file for this device even without kernel support. But best to fix the kernel first to make it work, without that you won't get far.

Either way, closing because we'll need a PR for the `.tablet` file and libwacom can't do anything about the device not working.
