### ISSUE TITLE
GAOMON S620 is detected as Huion H950P in GNOME Settings

### ISSUE THREAD

**Issue by kreaninw** [linuxwacom/libwacom#556]
The issue is caused by the generated `/usr/lib/udev/hwdb.d/65-libwacom.hwdb` file that's missing these lines under `# GAOMON S620`:

```
libwacom:name:* Dial:input:b0003v256Cp006D*
 ID_INPUT_TABLET_PAD=1

libwacom:name:* Touch Strip:input:b0003v256Cp006D*
 ID_INPUT_TABLET_PAD=1
```

See more about this issue: GNOME Settings issue [#2018](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2018).

**Comment by whot** [comment]
Summarising from the above linked GNOME settings issue:
- The device uses the same VID/PID as the HUION devices
- the device itself shows up in `libwacom-list-local-devices` as `GAOMON S620`, albeit only for the `Pen` and `Pad` nodes
- the other two nodes (`GAOMON Gaomon Tablet Touch Strip` and `GAOMON Gaomon Tablet Dial`) show up as `Huion H950P` because of the catchall VID/PID match in that file. That is because `TABLET_PAD` isn't set for those devices.

So the easy solution is to set `ID_INPUT_TABLET_PAD` for this device. Except then we have the issue of the touch strip appearing as configurable device when the device doesn't actually have a touch strip.

A possible fix for that would be to have the `Touch Strip` set `ID_INPUT_TABLET=0` to effectively unset the device. But this may be too much effort, might be easier to just live with the touch strip appearing.

**Comment by whot** [comment]
After searching around a bit: this device has neither a dial nor a touch strip, is this correct?

**Comment by kreaninw** [comment]
Yes, this device doesn't have a dial or a touch strip. Here's **[the official site of the device](https://www.gaomon.net/Pen_Tablet/S620.html)**.

**Comment by whot** [comment]
ok, thanks. I think in that case it may be better to narrow the current match for the H950P rather than adding the dial/touch strip for the S620. This way the dial/touch strip shouldn't get `ID_INPUT_TABLET` and "disappear" from libwacom's and thus GNOME's view.
