### ISSUE TITLE
deactivate touchscreen only, not stylus? udev

### ISSUE THREAD

**Issue by joh4nd** [linuxwacom/libwacom#591]
Hi,

Is it possible to deactivate Wacom touch screen while keep stylus/tablet alive? Can you help?

I have tried using udev rules, but my attempts have been unsuccessful. [See my SE unix question](https://unix.stackexchange.com/questions/756097/extra-udev-rule-to-keep-wacom-stylus-turned-on-while-disabling-wacom-touchscreen).

The machine runs Debian bullseye, oldstable.

**Comment by whot** [comment]
libwacom is merely a glorified text file database, it has no effect on the functionality of the tablet itself.

Your bug is likely in the [X11 wacom driver](https://github.com/linuxwacom/xf86-input-wacom/) or, if you're on Wayland, in [libinput](https://gitlab.freedesktop.org/libinput/libinput/issues) (or possibly the compositor). libinput can [ignore specific devices](https://wayland.freedesktop.org/libinput/doc/latest/ignoring-devices.html#ignoring-devices) though usually touch arbitration is on for pen + touch, i.e. the touch screen does not send events while the pen is being used. If that doesn't work, it's a libinput bug, please file it there.

**Comment by mtlg** [comment]
I use a script to toggle only the touchscreen on an ASUS ZenBook Duo 14 (change the IDs to match your device):

`#!/bin/sh

if test $(xinput --list-props 'ELAN9009:00 04F3:2C1B' | awk '/Device Enabled/ { print $NF; } { next; }') -ne 0; then
    xinput disable pointer:'ELAN9009:00 04F3:2C1B'
    xinput disable pointer:'ELAN9008:00 04F3:2D55'
else
    xinput enable pointer:'ELAN9009:00 04F3:2C1B'
    xinput enable pointer:'ELAN9008:00 04F3:2D55'
fi
`

**Comment by joh4nd** [comment]
@mtlg do you mind sharing your approach to find the device IDs?

And just to be clear, does your bash program discriminate between stylus and touch?
