### ISSUE TITLE
Touchscreen of Lenovo X1 Yoga Gen 2 not working properly

### ISSUE THREAD

**Issue by Jan-NiklasB** [linuxwacom/libwacom#629]
- **Device name**: Lenovo X1 Yoga - Wacom Touchscreen
- **Device model identifier**: X1 Yoga Gen 2 (?)
- **libwacom version**: 2.2.0-1

- [X ] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

# Bug description
The input from the touchscreen has a terrible resolution in Linux, most probably the driver doesn't work right.
After searching the web for a solution i finally guess that Wacom / Lenovo changed the device-id of the wacom touchpad they used in the Lenovo X1 Yoga gen2.

As stated here: [Link](https://wiki.gentoo.org/wiki/Lenovo_ThinkPad_X1_Yoga_2nd_Generation) the id should be `056a:50b8`  while mine is `Bus 001 Device 006: ID 056a:50b5 Wacom Co., Ltd Pen and multitouch sensor`

Also `libwacom-list-local-devices` gives me the following output:
```
/dev/input/event8 is a tablet but not supported by libwacom
Failed to find any devices known to libwacom.
```

Any ideas on how to fix this?

**Comment by whot** [comment]
> The input from the touchscreen has a terrible resolution in Linux, most probably the driver doesn't work right.

This bit has to be done in the kernel driver, cc @jigpu

> Failed to find any devices known to libwacom.

This bit can be fixed by adding the ID to the respective `.tablet` file that libwacom already has for the Yoga (`git grep` should show it). I'd appreciate it if you could file a PR for this, I'm closing this bug in the meantime.


>  X1 Yoga Gen 2 (?)

`cat /sys/class/dmi/id/modalias` probably has the proper name for this device.
